### ISSUE TITLE
bug report: packageRestore is set as false in libbitcoin/builds/msvc/nuget.config

### ISSUE THREAD

**Issue by GingerMoon** [libbitcoin/libbitcoin-build#159]

**Comment by evoskuil** [comment]
Hi, how is this a bug?

**Comment by GingerMoon** [comment]
Hi @evoskuil,
Thank you for looking into it. 
The reason why I think it is a bug is because I cannot think of any reason to set pakageRestore as false.
By default, after I cloned the project and run the build.bat or built it via vs2017, I got an error which can be solved by setting packageRestore as true.
So I set it as true in the vs2017, however, I still got the error and after I open the configuration in vs2017 again, the pakageRestore is still set as false.
Later I found this file libbitcoin/builds/msvc/nuget.config, and change the corresponding part and built the lib without error.
Please feel free to let me know if you set packageRestore as false on purpose or by design.

**Comment by GingerMoon** [comment]
Dear @evoskuil 
Thank you very much for the reply and the clarification! 
It makes sense.
