### ISSUE TITLE
Add support for Visual Studio 2019

### ISSUE THREAD

**Issue by varsnotwars** [libbitcoin/libbitcoin-build#202]
_As mentioned by @ldz1 in https://github.com/libbitcoin/libbitcoin-system/pull/1132#issuecomment-524588979_ these are some dependencies that may need updating to add support for VS2019:
- boost vc142

**Comment by evoskuil** [comment]
Boost is available (and I've integrated it) and I'll be updating the other dependencies soon (secp256k1 is published). Also will be adding VS 2019 to generation and dropping support for VS 2013 (CTP C++11 compiler).

**Comment by pmienk** [comment]
Currently supporting vs2022, closing
