### ISSUE TITLE
Create dependencies independently 

### ISSUE THREAD

**Issue by ldz1** [libbitcoin/libbitcoin-build#210]
Hello.

Libbitcoin for Windows is based on boost dependencies created by third parties. I suggest to replace them with dependencies built by libbitcoin community. That would give us a better control. 

I suppose boost was built without the icu dependency. Because of that the icu backend is missing. See for more info:
https://github.com/libbitcoin/libbitcoin-system/issues/1104
https://github.com/libbitcoin/libbitcoin-system/issues/1029

There is a workaround now:
https://github.com/libbitcoin/libbitcoin-system/pull/1155

But I believe it would be cleaner to run the boost ICU.

I recently built boost with icu myself for my testing purposes on msvc 14.1. The icu backend is loading now. I tried with the latest version (boost 1.71 and icu 65.1). In this variant, all three backends (winapi, std, icu) work properly and normalize as expected here https://github.com/libbitcoin/libbitcoin-system/blob/master/test/unicode/unicode.cpp#L55

Creating your libraries also facilitates support for VS 2019.
https://github.com/libbitcoin/libbitcoin-build/issues/202

**Comment by evoskuil** [comment]
Sure, just create the complete set of Nuget packages for 2013CTP, 2015, 2017 and 2019 with ICU, NDebug/Debug and any other options we build with in the non-Windows builds. The changes to libbitcoin are trivial at that point.

**Comment by evoskuil** [comment]
Good observation that the ICU issue is in the NuGet packages.

**Comment by evoskuil** [comment]
I've updated secp256k1 and will be updating libzmq shortly. Once I complete the vc142 update (vs2019) I'll add those packages. Boost has NuGet 1.72.0 packages through vc142 as well. https://www.nuget.org/packages/boost-vc142/

**Comment by evoskuil** [comment]
Thanks a lot for the observation on Boost ICU!!
