### ISSUE TITLE
Add AppVeyor build check for generate.cmd

### ISSUE THREAD

**Issue by ldz1** [libbitcoin/libbitcoin-build#218]
There is a CI build integrated with Travis which runs the generate.sh. I believe it makes sense to add a similar check for generate.cmd and AppVeyor.

(My PR https://github.com/libbitcoin/libbitcoin-build/pull/217 has probably corrupted the Windows build. This PR contains changes for gsl.copy_properties.sh and the cmd version needs similar changes. So far, I have verified the artifacts against Linux only.)

**Comment by evoskuil** [comment]
There is an appveyor build, but enabled only for libbitcoin-system.

https://ci.appveyor.com/project/pmienk/libbitcoin-system

**Comment by ldz1** [comment]
Right, but this build probably doesn't help much. 

libbitcoin-system build: builds libbitcoin-system from source
libbitcoin-build (travis): generates artifacts on linux
libbitcoin-build (appveyor): should generate artifacts on windows which is unfortunately missing.

**Comment by ldz1** [comment]
Btw, why is libbitcoin-system the only repository that contains windows builds?

**Comment by evoskuil** [comment]
All repos do, just appveyor limits.

**Comment by ldz1** [comment]
Forgive me imprecision. I though about why only libbitcoin-sytem is built on appveyor. 

"just appveyor limits."

It's a pity. So my issue probably cannot be solved :/. At least using the appveyor CI. Maybe there are any alternatives?

**Comment by evoskuil** [comment]
Yes, it was really a test case.

**Comment by ldz1** [comment]
As we discussed on slack, the limits mainly apply to 60 minutes, which should not be a problem for libbitcoin-build. The tricky part could be to run gsl on AppVeyor.

The priority of this issue is rather low. However, having such a verification wouldn't hurt.

**Comment by evoskuil** [comment]
Can be preinstalled as a binary dependency. We did this in the -system build for the VS 2013 CTP compiler.
