### ISSUE TITLE
--with[out]-doc flag wanted

### ISSUE THREAD

**Issue by tieugene** [libbitcoin/libbitcoin-build#222]
As for Fedora Linux build system it is possible to define doc files.
But libbitcoin-* installers put all of them into doc directory without any question.
So I need to do (during packaging into rpm):
```
%install
%{make_install}
rm -rf %{buildroot}%{_docdir}
...
%files
%doc AUTHORS README.md
```
(other doc files not required in rpm-packaged application)

**Comment by evoskuil** [comment]
Pull requests welcome. Note that all build artifacts are generated.

**Comment by evoskuil** [comment]
The Libbitcoin installers don’t intend to reproduce all options available in autotools. A manual autotools build remains available and supported. The installers are meant to help inexperienced users deploy. Keeping them simple is a priority.
