### ISSUE TITLE
Cleaning / arrangement of msvc build scripts

### ISSUE THREAD

**Issue by ldz1** [libbitcoin/libbitcoin-build#232]
There are five scripts inside libbitcoin-build/props/build/. Some appear to be outdated. The missing one build_all.bat was mentioned by https://github.com/libbitcoin/libbitcoin-build/issues/132 There is also a statement inside libbitcoin-system about dynamic build config that doesn't build https://github.com/libbitcoin/libbitcoin-system#build-libbitcoin-projects. Besides, there are some past optimized build configs (LTCG).

The status should be clarified

**Comment by evoskuil** [comment]
What do you mean by “past optimized”?

**Comment by ldz1** [comment]
I wanted to say some of the old scripts build with LTCG, which is no longer used in current scripts, perhaps for rational reasons.

**Comment by evoskuil** [comment]
Can you clarify, what's an old vs. new script. All of the artifacts are generated.

**Comment by ldz1** [comment]
https://github.com/libbitcoin/libbitcoin-build/tree/master/props/build

Old scripts:
buildbase_all.bat
buildbase_static_all.bat
buildbase_static_ltcg.bat
buildbase_static_x64.bat

New scripts:
build_base.bat
build_all.bat (missing in libbitcoin-build)

I mean, these "old" scripts are missing inside libbitcoin-*/builds/mscv/build. See for instance https://github.com/libbitcoin/libbitcoin-system/tree/master/builds/msvc/build That's why I'm asking if it's intentional or are these old scripts obsolete and can be deleted?

**Comment by evoskuil** [comment]
These are cloned from https://github.com/evoskuil/visual-studio-template/tree/master/build
