### ISSUE TITLE
Travis builds are slow and sometimes killed.

### ISSUE THREAD

**Issue by evoskuil** [libbitcoin/libbitcoin-build#53]
Move our Travis executions to their containers model. This only requires removing sudo from all installs.

**Comment by pmienk** [comment]
Addressed by #81.  The https://github.com/libbitcoin/libbitcoin-explorer project still requires more time than my private repository allows, but appears significantly reduced.

**Comment by evoskuil** [comment]
This is sometimes still an issue, but the main problem is resolved by moving to containers, so closing.
